AWSTemplateFormatVersion: "2010-09-09"

Description: "CloudFormation template for VPC creation"

# Parâmetros para personalizar a implantação
Parameters:
  VPCCidrBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: The CIDR block for the VPC

  PublicSubnet1CIDR:
    Type: String
    Default: 10.0.1.0/24
    AllowedValues:
      - 10.0.1.0/24
      - 10.0.2.0/24
      - 10.0.3.0/24
    Description: The CIDR block for the public subnet 1
    ConstraintDescription: must be one of the allowed range

  PrivateSubnet1CIDR:
    Type: String
    Default: 10.0.4.0/24
    AllowedValues:
      - 10.0.4.0/24
      - 10.0.5.0/24
      - 10.0.6.0/24
    Description: The CIDR block for the private subnet 1
    ConstraintDescription: must be one of the allowed range

  PrivateSubnet2CIDR:
    Type: String
    Default: 10.0.8.0/24
    AllowedValues:
      - 10.0.8.0/24
      - 10.0.9.0/24
      - 10.0.10.0/24
    Description: The CIDR block for the private subnet 2
    ConstraintDescription: must be one of the allowed range

  EnvironmentType:
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Production
    Description: Environment type
    ConstraintDescription: must be one of the allowed values

# Criação dos recursos de rede, incluindo a VPC, sub-redes públicas e privadas, gateway de internet e tabelas de rotas.
Resources:
 # Cria a VPC com suporte a DNS e especifica seu bloco CIDR.
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}"
        - Key: Environment
          Value: !Sub "${EnvironmentType}"

  # Cria um Internet Gateway e o associa à VPC.
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-IGW"
        - Key: Environment
          Value: !Sub "${EnvironmentType}"

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  # Cria a primeira sub-rede pública e permite atribuir endereços IP públicos automaticamente.
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Public Subnet 1"
        - Key: Environment
          Value: !Sub "${EnvironmentType}"

  # Cria a primeira sub-rede privada
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Private Subnet 1"
        - Key: Environment
          Value: !Sub "${EnvironmentType}"

  # Cria a segunda sub-rede privada
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Private Subnet 2"
        - Key: Environment
          Value: !Sub "${EnvironmentType}"

  # Cria uma tabela de rotas para a sub-rede pública.
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Public Route Table"
        - Key: Environment
          Value: !Sub "${EnvironmentType}"

  # Cria uma tabela de rotas para as sub-redes privadas.
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Private Route Table"
        - Key: Environment
          Value: !Sub "${EnvironmentType}"

  # Associa a tabela de rotas privada à primeira sub-rede privada.
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet1

  # Associa a tabela de rotas privada à segunda sub-rede privada.
  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet2

  # Cria a rota padrão para a internet na tabela de rotas pública, usando o Internet Gateway.
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Associa a tabela de rotas pública à primeira sub-rede pública.
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

# Saídas para exportar os IDs dos recursos criados, como a VPC e as sub-redes.
Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1ID"

  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet1ID"

  PrivateSubnet2:
    Description: A reference to the private subnet in the 2nd Availability Zone
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet2ID"
