template-file-path: vpc-stack.yaml
parameters:
  VPCCidrBlock: 10.0.0.0/16
  PublicSubnet1CIDR: 10.0.1.0/24
  PrivateSubnet1CIDR: 10.0.4.0/24
  PrivateSubnet2CIDR: 10.0.8.0/24
  EnvironmentType: Development
tags: {}
